# Generated by Django 4.1.3 on 2022-12-12 04:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reting',
            new_name='Rating',
        ),
    ]
